### ISSUE TITLE
Add support for virtual rows & static valueUrl

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-parser-csvw#1]
The following mapping 

```json
        "virtual": true,
        "propertyUrl": "rdf:type",
        "valueUrl": "http://vocab.performing-arts.ch/E5"
```

Should create a rdf:type triple

**Comment by ktk** [comment]
Update: seems to work as long as propertyUrl is not prefixed

**Comment by ktk** [comment]
@bergos looks broken in current release

**Comment by bergos** [comment]
Fixed in the latest git version and also includes tests for this feature.
