### ISSUE TITLE
Support suppressOutput

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-parser-csvw#2]
Given the following colum:

```
      {
        "titles": "Geodaten",
        "suppressOutput": true
      }
```
by specifying `suppressOutput: true` the column should be ignored and no triples should be generated. Currently it creates a triple with `<undefined>` as predicate.

**Comment by bergos** [comment]
Added with [this commit](https://github.com/rdf-ext/rdf-parser-csvw/commit/58982c7a8ba8159588f90b2d5430b0ba6ea2a71c).

**Comment by ktk** [comment]
works fine tnx
