### ISSUE TITLE
Support for datatype

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-parser-csvw#3]
CSVW defines a bunch of [data types](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#parsing-cells), this should be a work in progress issue but the minimal one to implement should be `number` and `integer` for a start. The rest can be added once we have the need for it.

The `base` stuff for defining own data types can also be ignored at the moment.

**Comment by bergos** [comment]
Added with [this commit](https://github.com/rdf-ext/rdf-parser-csvw/commit/1437cadb534cc78e081d0c0aaee51a6f5de8ab8f).
